routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');


Route::resource('contactInfos', 'Contact_infoController');

Route::resource('people', 'PersonController');


Route::resource('people', 'PersonController');

Route::resource('contactInfos', 'Contact_infoController');

Route::resource('people', 'PersonController');

Route::resource('contactInfos', 'Contact_infoController');

app/Models/Contact_info.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Contact_info
 * @package App\Models
 * @version April 24, 2019, 5:08 pm UTC
 *
 * @property \App\Models\Person person
 * @property string calle
 * @property string num_calle
 * @property string puerta_piso
 * @property string cp
 * @property string ciudad
 * @property string isla
 * @property string email
 * @property string whatsapp
 * @property string telefono_domi
 * @property string movil
 * @property integer person_id
 */
class Contact_info extends Model
{
    use SoftDeletes;

    public $table = 'contact_infos';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'calle',
        'num_calle',
        'puerta_piso',
        'cp',
        'ciudad',
        'isla',
        'email',
        'whatsapp',
        'telefono_domi',
        'movil',
        'person_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'calle' => 'string',
        'num_calle' => 'string',
        'puerta_piso' => 'string',
        'cp' => 'string',
        'ciudad' => 'string',
        'isla' => 'string',
        'email' => 'string',
        'whatsapp' => 'string',
        'telefono_domi' => 'string',
        'movil' => 'string',
        'person_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     **/
    public function person()
    {
        return $this->hasOne(\App\Models\Person::class, 'person_id', 'id');
    }
}

app/Http/Controllers/Contact_infoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateContact_infoRequest;
use App\Http\Requests\UpdateContact_infoRequest;
use App\Repositories\Contact_infoRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class Contact_infoController extends AppBaseController
{
    /** @var  Contact_infoRepository */
    private $contactInfoRepository;

    public function __construct(Contact_infoRepository $contactInfoRepo)
    {
        $this->contactInfoRepository = $contactInfoRepo;
    }

    /**
     * Display a listing of the Contact_info.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $contactInfos = $this->contactInfoRepository->all();

        return view('contact_infos.index')
            ->with('contactInfos', $contactInfos);
    }

    /**
     * Show the form for creating a new Contact_info.
     *
     * @return Response
     */
    public function create()
    {
        return view('contact_infos.create');
    }

    /**
     * Store a newly created Contact_info in storage.
     *
     * @param CreateContact_infoRequest $request
     *
     * @return Response
     */
    public function store(CreateContact_infoRequest $request)
    {
        $input = $request->all();

        $contactInfo = $this->contactInfoRepository->create($input);

        Flash::success('Contact Info saved successfully.');

        return redirect(route('contactInfos.index'));
    }

    /**
     * Display the specified Contact_info.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $contactInfo = $this->contactInfoRepository->find($id);

        if (empty($contactInfo)) {
            Flash::error('Contact Info not found');

            return redirect(route('contactInfos.index'));
        }

        return view('contact_infos.show')->with('contactInfo', $contactInfo);
    }

    /**
     * Show the form for editing the specified Contact_info.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $contactInfo = $this->contactInfoRepository->find($id);

        if (empty($contactInfo)) {
            Flash::error('Contact Info not found');

            return redirect(route('contactInfos.index'));
        }

        return view('contact_infos.edit')->with('contactInfo', $contactInfo);
    }

    /**
     * Update the specified Contact_info in storage.
     *
     * @param int $id
     * @param UpdateContact_infoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateContact_infoRequest $request)
    {
        $contactInfo = $this->contactInfoRepository->find($id);

        if (empty($contactInfo)) {
            Flash::error('Contact Info not found');

            return redirect(route('contactInfos.index'));
        }

        $contactInfo = $this->contactInfoRepository->update($request->all(), $id);

        Flash::success('Contact Info updated successfully.');

        return redirect(route('contactInfos.index'));
    }

    /**
     * Remove the specified Contact_info from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $contactInfo = $this->contactInfoRepository->find($id);

        if (empty($contactInfo)) {
            Flash::error('Contact Info not found');

            return redirect(route('contactInfos.index'));
        }

        $this->contactInfoRepository->delete($id);

        Flash::success('Contact Info deleted successfully.');

        return redirect(route('contactInfos.index'));
    }
}

resources/views/contact_infos/create.blade.php
@extends('layouts.home')
@section('title', "Create")
@section('content')

<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Contact Info</h1>
    @include('laradminbs4-templates::common.errors')
    <br>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Insert Register</h6>
        </div>
        <div class="card-body">
            {!! Form::open(['route' => 'contactInfos.store']) !!}

            @include('contact_infos.fields')

            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/contact_infos/edit.blade.php
@extends('layouts.home')
@section('title', "Edit")
@section('content')

<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Contact Info</h1>
    <br>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edition</h6>
        </div>
        <div class="card-body">
            {!! Form::model($contactInfo, ['route' => ['contactInfos.update', $contactInfo->id], 'method' => 'patch']) !!}

            @include('contact_infos.fields')

            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/contact_infos/fields.blade.php
<!-- Calle Field -->
<div class="form-group col-sm-6">
    {!! Form::label('calle', 'Calle:') !!}
    {!! Form::text('calle', null, ['class' => 'form-control']) !!}
</div>

<!-- Num Calle Field -->
<div class="form-group col-sm-6">
    {!! Form::label('num_calle', 'Num Calle:') !!}
    {!! Form::text('num_calle', null, ['class' => 'form-control']) !!}
</div>

<!-- Puerta Piso Field -->
<div class="form-group col-sm-6">
    {!! Form::label('puerta_piso', 'Puerta Piso:') !!}
    {!! Form::text('puerta_piso', null, ['class' => 'form-control']) !!}
</div>

<!-- Cp Field -->
<div class="form-group col-sm-6">
    {!! Form::label('cp', 'Cp:') !!}
    {!! Form::text('cp', null, ['class' => 'form-control']) !!}
</div>

<!-- Ciudad Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ciudad', 'Ciudad:') !!}
    {!! Form::text('ciudad', null, ['class' => 'form-control']) !!}
</div>

<!-- Isla Field -->
<div class="form-group col-sm-6">
    {!! Form::label('isla', 'Isla:') !!}
    {!! Form::select('isla', [' Tenerife' => ' Tenerife', ' El Hierro' => ' El Hierro', ' La Palma' => ' La Palma', ' La Gomera' => ' La Gomera', ' Gran Canaria' => ' Gran Canaria', ' Fuerteventura' => ' Fuerteventura', ' Lanzarote' => ' Lanzarote'], null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Telefono Domi Field -->
<div class="form-group col-sm-6">
    {!! Form::label('telefono_domi', 'Telefono Domi:') !!}
    {!! Form::text('telefono_domi', null, ['class' => 'form-control']) !!}
</div>

<!-- Movil Field -->
<div class="form-group col-sm-6">
    {!! Form::label('movil', 'Movil:') !!}
    {!! Form::text('movil', null, ['class' => 'form-control']) !!}
</div>

<!-- Person Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('person_id', 'Person Id:') !!}
    {!! Form::text('person_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('contactInfos.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/contact_infos/index.blade.php
@extends('layouts.home')
@section('title', "Tables")
@push('css')
    <link href="{{mix('vendor/datatable/css/datatable.css')}}" rel="stylesheet">
@endpush
@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Contact Infos</h1>
    <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
            <h1 class="float-sm-right">
                <a class="btn btn-primary" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('contactInfos.create') !!}">Add New</a>
            </h1>
            <div class="clearfix"></div>
            @include('flash::message')
        </div>
    <div class="card-body">
        <div class="table-responsive">
            @include('contact_infos.table')
        </div>
    </div>
    </div>
</div>
@endsection
@push('scripts')
    <script src="{{mix('vendor/datatable/js/datatable.js')}}"></script>
    <script src="{{asset('vendor/datatable/js/datatables-init.js')}}"></script>
@endpush

resources/views/contact_infos/show.blade.php
@extends('layouts.home')
@section('title', "Show")
@section('content')

<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Contact Info</h1>
    <br>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Datos Generales</h6>
        </div>
        <div class="card-body">
            @include('contact_infos.show_fields')
            <a href="{!! route('contactInfos.index') !!}" class="btn btn-primary">Back</a>
        </div>
    </div>
</div>
@endsection

resources/views/contact_infos/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $contactInfo->id !!}</p>
</div>

<!-- Calle Field -->
<div class="form-group">
    {!! Form::label('calle', 'Calle:') !!}
    <p>{!! $contactInfo->calle !!}</p>
</div>

<!-- Num Calle Field -->
<div class="form-group">
    {!! Form::label('num_calle', 'Num Calle:') !!}
    <p>{!! $contactInfo->num_calle !!}</p>
</div>

<!-- Puerta Piso Field -->
<div class="form-group">
    {!! Form::label('puerta_piso', 'Puerta Piso:') !!}
    <p>{!! $contactInfo->puerta_piso !!}</p>
</div>

<!-- Cp Field -->
<div class="form-group">
    {!! Form::label('cp', 'Cp:') !!}
    <p>{!! $contactInfo->cp !!}</p>
</div>

<!-- Ciudad Field -->
<div class="form-group">
    {!! Form::label('ciudad', 'Ciudad:') !!}
    <p>{!! $contactInfo->ciudad !!}</p>
</div>

<!-- Isla Field -->
<div class="form-group">
    {!! Form::label('isla', 'Isla:') !!}
    <p>{!! $contactInfo->isla !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $contactInfo->email !!}</p>
</div>

<!-- Whatsapp Field -->
<div class="form-group">
    {!! Form::label('whatsapp', 'Whatsapp:') !!}
    <p>{!! $contactInfo->whatsapp !!}</p>
</div>

<!-- Telefono Domi Field -->
<div class="form-group">
    {!! Form::label('telefono_domi', 'Telefono Domi:') !!}
    <p>{!! $contactInfo->telefono_domi !!}</p>
</div>

<!-- Movil Field -->
<div class="form-group">
    {!! Form::label('movil', 'Movil:') !!}
    <p>{!! $contactInfo->movil !!}</p>
</div>

<!-- Person Id Field -->
<div class="form-group">
    {!! Form::label('person_id', 'Person Id:') !!}
    <p>{!! $contactInfo->person_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $contactInfo->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $contactInfo->updated_at !!}</p>
</div>

resources/views/contact_infos/table.blade.php
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Calle</th>
        <th>Num Calle</th>
        <th>Puerta Piso</th>
        <th>Cp</th>
        <th>Ciudad</th>
        <th>Isla</th>
        <th>Email</th>
        <th>Whatsapp</th>
        <th>Telefono Domi</th>
        <th>Movil</th>
        <th>Person Id</th>
            <th>Action</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>Calle</th>
        <th>Num Calle</th>
        <th>Puerta Piso</th>
        <th>Cp</th>
        <th>Ciudad</th>
        <th>Isla</th>
        <th>Email</th>
        <th>Whatsapp</th>
        <th>Telefono Domi</th>
        <th>Movil</th>
        <th>Person Id</th>
            <th>Action</th>
        </tr>
    </tfoot>
    <tbody>
    @foreach($contactInfos as $contactInfo)
        <tr>
            <td>{!! $contactInfo->calle !!}</td>
            <td>{!! $contactInfo->num_calle !!}</td>
            <td>{!! $contactInfo->puerta_piso !!}</td>
            <td>{!! $contactInfo->cp !!}</td>
            <td>{!! $contactInfo->ciudad !!}</td>
            <td>{!! $contactInfo->isla !!}</td>
            <td>{!! $contactInfo->email !!}</td>
            <td>{!! $contactInfo->whatsapp !!}</td>
            <td>{!! $contactInfo->telefono_domi !!}</td>
            <td>{!! $contactInfo->movil !!}</td>
            <td>{!! $contactInfo->person_id !!}</td>
            <td>
                {!! Form::open(['route' => ['contactInfos.destroy', $contactInfo->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('contactInfos.show', [$contactInfo->id]) !!}" class='btn btn-primary btn-xs'><i class="far fa-eye"></i></a>
                    <a href="{!! route('contactInfos.edit', [$contactInfo->id]) !!}" class='btn btn-primary btn-xs'><i class="far fa-edit"></i></a>
                    {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>