routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');


Route::resource('contactInfos', 'Contact_infoController');

Route::resource('people', 'PersonController');


Route::resource('people', 'PersonController');

Route::resource('contactInfos', 'Contact_infoController');

Route::resource('people', 'PersonController');

Route::resource('contactInfos', 'Contact_infoController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }} - @yield('loginTitle')</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body class="bg-gradient-primary">
    <div class="container-fluid">
        @yield('content')
    </div>


    <!-- Bootstrap core JavaScript, Core plugin JavaScript, Page level plugins -->
    <script src="{{mix('js/app.js')}}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{mix('js/customJs/custom.js')}}"></script>

</body>

</html>

resources/views/layouts/menu.blade.php
<!-- Divider -->
<hr class="sidebar-divider">
<li class="{{ Request::is('people*') ? 'active' : '' }} nav-item">
    <a class="nav-link" href="{!! route('people.index') !!}"><i class="fas fa-fw fa-table"></i><span>People</span></a>
</li>

<!-- Divider -->
<hr class="sidebar-divider">
<li class="{{ Request::is('contactInfos*') ? 'active' : '' }} nav-item">
    <a class="nav-link" href="{!! route('contactInfos.index') !!}"><i class="fas fa-fw fa-table"></i><span>Contact Infos</span></a>
</li>

resources/views/layouts/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('adminIndex') }}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{ url('#') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>
    <!-- Sidebar Menu -->
    @include('layouts.menu')

    <!-- Divider -->
    
    <hr class="sidebar-divider">
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>